// packages/examples/react-todo/src/App.tsx
import { createStore } from '@atomx-fast/core';
import { useAtom } from '@atomx/react';
import { useState } from 'react';

const store = createStore();

export default function App() {
  const list = useAtom(store.todos.allAtom);
  const [text, setText] = useState('');
  const add = () => {
    store.todos.set(Date.now().toString(), { text, done: false });
    setText('');
  };
  return (
    <>
      <h1>AtomX React Todo</h1>
      <input value={text} onChange={(e) => setText(e.target.value)} />
      <button onClick={add}>add</button>
      <ul>
        {list.map((t) => (
          <Row key={t.id} id={t.id} />
        ))}
      </ul>
    </>
  );
}

function Row({ id }: { id: string }) {
  const todo = useAtom(store.todos.byId(id))!;
  return (
    <li>
      <input
        type="checkbox"
        checked={todo.done}
        onChange={(e) => store.todos.set(id, { done: e.target.checked })}
      />
      {todo.text}
    </li>
  );
}

// packages/examples/vue-todo/src/App.vue
<template>
  <h1>AtomX Vue Todo</h1>
  <input v-model="text" @keyup.enter="add" />
  <button @click="add">add</button>
  <ul>
    <Row v-for="t in list" :key="t.id" :id="t.id" />
  </ul>
</template>

<script setup lang="ts">
import { createStore } from '@atomx-fast/core';
import { useAtom } from '@atomx/vue';
import { ref } from 'vue';

const store = createStore();
const list = useAtom(store.todos.allAtom);
const text = ref('');

function add() {
  store.todos.set(Date.now().toString(), { text: text.value, done: false });
  text.value = '';
}
</script>
